spring:
  data:
    mongodb:
      authentication-database: offers_db_prod
      username: api_user_prod
      password: apipwd
      database: offers_db_prod
      port: 27017
      host: localhost
      auto-index-creation: true
      collection: selection_offers