version: '4.3'
services:
  mongodb:
    image: mongo:8.0.0-rc7
    container_name: mongodb
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./docker-entrypoint-initdb.d/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    command:
      - --auth

  microservice1:
    container_name: microservice1
    build:
      context: mc1
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - microservice2

  microservice2:
    container_name: microservice2
    build:
      context: mc2
      dockerfile: Dockerfile
    ports:
      - 8081:8081
    depends_on:
      - mongodb